
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: rayh
    password: 40028922

  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: ERROR